# Generated by Django 3.2.12 on 2022-04-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_auto_20220426_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='cvd',
            field=models.FloatField(default=0, null=True, verbose_name='Вероятность ССЗ (%)'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='cvd_non',
            field=models.FloatField(default=0, null=True, verbose_name='Вероятность отсутствия ССЗ (%)'),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='fullname',
            field=models.CharField(max_length=150, null=True, verbose_name='ФИО'),
        ),
    ]
